Propagate liche exit code
peter-evans/link-checker pull request #17
Opened 2020-01-18 04:38 UTC by gecko655

The current link-checker action returns 0 regardless of errors found since it returns the return code of `cat`.
To mark failure on the pull request page, the action should output "whether errors are found or not".

2020-01-20 01:26 UTC, peter-evans requested changes
Thank you for contributing!

This action intentionally doesn't fail when there are link errors. If I accept this as-is it would be a breaking behaviour change for the action. I would like to support your use case so I have one small change that would allow me to merge this.

Instead of returning the exit code (which would fail the action)...
```
exit $exit_code
```
... create an output variable that can be checked in the workflow.
```
echo ::set-output name=exit_code::$exit_code
```

Then in your workflow you can fail when there are link errors like this:
```
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      id: lc
      uses: peter-evans/link-checker@v1.1.0
      with:
        args: -v -r *
    - name: Fail if there where link errors
       run: exit ${{ steps.lc.outputs.exit_code }}
```

2020-01-20 01:26 UTC, peter-evans commented on entrypoint.sh
> +exit $exit_code
```suggestion
echo ::set-output name=exit_code::$exit_code
```

2020-01-21 14:54 UTC, gecko655 commented
Thank you for reviewing!
I've applied your suggestion.

2020-01-22 03:55 UTC, peter-evans approved these changes
Thank you!

2020-01-22 03:55 UTC, merged